### ISSUE TITLE
Impossible to use string constant or enum as a callback argument

### ISSUE THREAD

**Issue by romantaranenko** [winzou/state-machine#50]
A configuration like that is impossible to use

```
       callbacks:
            after:
                on_initial_fraud_pass:
                    on: !php/const Services\Account\Constants\FraudStateTransition::INITIAL_FRAUD_PASS
                    do: Services\Account\State\TransitionCallbackManager::transitionUserState
                    args:
                        - 'object'
                        - !php/const Services\Account\Constants\AccountStateTransition::ACTIVATE
```

Since [expression parser is applied](https://github.com/winzou/state-machine/blob/master/src/SM/Callback/Callback.php#L65) and constant returns unquoted string
